# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: v1beta-ci

on:
  push:
    branches: [ v1beta ]
  pull_request:
    branches: [ v1beta ]
    types: [opened, synchronize]

jobs:
  build:

    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    environment: v1beta

    steps:
    - uses: actions/checkout@v2
    - name: uitest
      id: uitest
      run: npm install && npm test && npm run build && tree build
    - name: Push Build Artifacts
      if: github.event_name == 'push'
      uses: ec-release/github-action-copy-files-folders-to-another-repos@main
      env:
        API_TOKEN_GITHUB: ${{ secrets.DC_GITHUB_TKN }}
        GIT_USEREMAIL: ${{ secrets.DC_GITHUB_EMAIL }}
        GIT_USERNAME: ${{ secrets.DC_GITHUB_USER }}
      with:
        SOURCE_DIR: 'build'
        DESTINATION_REPOS_BRANCHES: 'github.com/dc-release/dc-portal.git:disty'
        COMMIT_MESSAGE: 'DC Bot Deployment'
    - name: prmerged
      if: github.event_name == 'push'
      id: prmerged
      run: |
        echo pr has been merged and closed
